### ISSUE TITLE
Confusing Questions Need Updating / Clarification

### ISSUE THREAD

**Issue by mathymitchell** [learn-co-curriculum/dsc-1-08-10-introduction-to-probability-lab#10]
Students in the current in person described spending over an hour being confused about the difference between these two questions:

"""
a. What is the probability of throwing a 5 at least once?

First, use sample_dice to get "True" values for each time a 5 occurs.

set_5 = None

Next, make sure that you get a value True for each pair where at least one 5 was thrown.

true_5 = None
print(true_5)
"""

Further clarification about combining booleans and what was intended here is warranted.

**Comment by LoreDirick** [comment]
@mathymitchell thanks for this feedback - very helpful. Updated for curr V1!
