### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by Socjon** [learn-co-curriculum/dsc-1-08-10-introduction-to-probability-lab#3]
> Now let's try creating your own event space!
> A teaching assistant is holding office hours so students can make appointments. She has 6 appointments scheduled today, 3 by male students, and 3 by female students.
> 
> Create a NumPy array te say way as we did this for you in the "throwing a dice twice" exercise. It will be quite a bit of typing, as your resulting NumPy array will have a shape (20,6)!

It was unclear of what you were looking for. A prompt of "How many ways can you fill the appointments" or "How many different ways can the students sign up for the appointments" would go a long way here.

**Comment by mathymitchell** [comment]
Feedback incorporated and typo fixed.
