### ISSUE TITLE
"te say way" - not even sure what this is trying to say.

### ISSUE THREAD

**Issue by witchlane** [learn-co-curriculum/dsc-1-08-10-introduction-to-probability-lab#9]
see screen shot below - not sure but think you are trying to say "array as we did this for you"....
![image](https://user-images.githubusercontent.com/44211854/51782198-852cf000-20f2-11e9-9874-e0d0e4566521.png)

**Comment by LoreDirick** [comment]
@witch

**Comment by LoreDirick** [comment]
@witchlane updated now, thanks!
